Adding unit tests for sample-code-java
Diffblue-benchmarks/sample-code-java pull request #2
Opened 2019-08-30 15:55 UTC by EdgarScott

I've analysed your codebase and noticed that it is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look further.

2019-08-30 15:57 UTC, EdgarScott commented
Starting with a clean branch seemed the easiest way to get rid of all those changed files.

2019-09-16 07:51 UTC, EdgarScott commented
@paulkennethkent this is the repo which Cover did not generate any good tests for. We thought it was because Cover doesn't test system.out

Do you want to submit this PR externally anyway, as it was a user request?

2019-09-17 08:35 UTC, paulkennethkent commented on src/test/java/net/authorize/sample/Sha512/ComputeTransHashSHA2Test.java
> +public class ComputeTransHashSHA2Test {
Please submit this class only. Remove all unnecessary dependencies.

2019-09-17 08:35 UTC, paulkennethkent requested changes
So comment above.

2019-09-17 08:50 UTC, closed without merging